name = "borderboxes-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[d1_databases]]
binding = "DB"
database_name = "borderboxes-db"
database_id = "ad60d8c3-63dc-45c5-8933-f3688e43ee24"

# For local dev
[vars]
TICK_HZ = "20"